import { StyleSheet, Platform } from 'react-native';

export const C = {
  deep:      '#2C6B7F',
  ocean:     '#3A7CA5',
  teal:      '#4ECDC4',
  tealLight: '#5DD9D2',
  steel:     '#627D98',
  charcoal:  '#3E4C59',
  snow:      '#F8FAFB',
  slate:     '#8B9DAF',
  mist:      '#EDF2F4',
  cloud:     '#D9E2EC',
  success:   '#4CAF50',
  warning:   '#F0A04B',
  error:     '#C0544A',
  info:      '#5B9BD5',
};

export const S = StyleSheet.create({
  card: {
    backgroundColor: 'rgba(248,250,251,0.97)',
    borderRadius: 20,
    shadowColor: '#ffffff',
    shadowOffset: { width: -6, height: -6 },
    shadowOpacity: 0.55,
    shadowRadius: 18,
    elevation: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.88)',
  },
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.65)',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.9)',
    shadowColor: '#ffffff',
    shadowOffset: { width: -3, height: -3 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 2,
  },
  listTitle: { fontSize: 13, fontWeight: '700', color: '#3E4C59', marginBottom: 2 },
  listSub:   { fontSize: 11, color: '#627D98' },
  listComment: { fontSize: 11, color: '#8B9DAF', marginTop: 3, fontStyle: 'italic' },
  sectionTitle: { fontSize: 16, fontWeight: '800', color: '#2C6B7F' },
  label: { fontSize: 11, fontWeight: '800', color: '#3E4C59', letterSpacing: 0.8, marginBottom: 7 },
  input: {
    backgroundColor: '#E4EDF1',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 13 : 10,
    fontSize: 13,
    color: '#3E4C59',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  inputFocused: { borderColor: '#4ECDC4', backgroundColor: '#f0fafa' },
  badge: { paddingVertical: 4, paddingHorizontal: 10, borderRadius: 20 },
  badgeText: { fontSize: 10, fontWeight: '800', letterSpacing: 0.3 },
  emptyText: { color: '#8B9DAF', fontSize: 13, textAlign: 'center', paddingVertical: 24 },
  tabCard: { flex: 1, marginBottom: 16 },
  tabScroll: { flex: 1 },
  tabScrollInner: { paddingHorizontal: 16, paddingBottom: 16 },
  tabContentPad: { padding: 16 },
  tabTitleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  addBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    borderRadius: 20, paddingVertical: 7, paddingHorizontal: 14,
    borderWidth: 1, borderColor: 'rgba(255,255,255,0.25)',
  },
  addBtnText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  modalOverlay: {
    flex: 1, backgroundColor: 'rgba(44,107,127,0.5)', justifyContent: 'flex-end',
  },
  modalCard: {
    borderBottomLeftRadius: 0, borderBottomRightRadius: 0,
    borderTopLeftRadius: 28, borderTopRightRadius: 28,
    padding: 24, paddingTop: 28,
  },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18 },
  modalTitle: { fontSize: 18, fontWeight: '900', color: '#2C6B7F' },
  modalSubmitBtn: {
    borderRadius: 14, paddingVertical: 14,
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 1, borderColor: 'rgba(255,255,255,0.25)',
  },
  modalSubmitText: { color: '#fff', fontSize: 14, fontWeight: '700', letterSpacing: 0.4 },
  toggleRow: {
    flexDirection: 'row', backgroundColor: 'rgba(237,242,244,0.8)',
    borderRadius: 12, padding: 4, gap: 4, marginBottom: 16,
  },
  toggleBtn: { flex: 1, paddingVertical: 9, alignItems: 'center', borderRadius: 10 },
  toggleBtnActive: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    shadowColor: '#ffffff', shadowOffset: { width: -3, height: -3 },
    shadowOpacity: 0.6, shadowRadius: 6, elevation: 3,
  },
  toggleText: { fontSize: 13, fontWeight: '600', color: '#8B9DAF' },
  toggleTextActive: { color: '#2C6B7F', fontWeight: '800' },
});